get http://localhost:8091/login?name=admin1@admin1.com&password=admin1

###

post http://localhost:8091/login?name=admin1@admin1.com&password=admin1
Content-Type: application/json

{
    "name": "admin1@admin1.com",
    "password": "admin1"
}

###

post http://localhost:8091/login?name=kk&password=kk
Content-Type: application/json

{
    "name": "falla",
    "password": "kk"
}

###

post http://localhost:8091/login
Content-Type: application/json

{
    "name": "admin1@admin1.com",
    "password": "admin1"
}

###

get http://localhost:8091/seguro
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluMUBhZG1pbjEuY29tIiwiYXV0aG9yaXRpZXMiOlsiR2VyZW50ZSJdLCJpYXQiOjE2NDg0NTY4NTksImV4cCI6MTY0ODQ1NzQ1OX0.Dbgw4Gg5CNEmmV1ikqf14wCOI65v94_zAOgNzTi9PYOO37Bx_H4Eor_c49fOV8Z98yjQlrImbcGq4vZD87L_BQ

###

get http://localhost:8091/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluMUBhZG1pbjEuY29tIiwiYXV0aG9yaXRpZXMiOlsiR2VyZW50ZSJdLCJpYXQiOjE2NDg0NTY4NTksImV4cCI6MTY0ODQ1NzQ1OX0.Dbgw4Gg5CNEmmV1ikqf14wCOI65v94_zAOgNzTi9PYOO37Bx_H4Eor_c49fOV8Z98yjQlrImbcGq4vZD87L_BQ

###

get http://localhost:8091/secreto
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluMUBhZG1pbjEuY29tIiwiYXV0aG9yaXRpZXMiOlsiR2VyZW50ZSJdLCJpYXQiOjE2NDg0NTY4NTksImV4cCI6MTY0ODQ1NzQ1OX0.Dbgw4Gg5CNEmmV1ikqf14wCOI65v94_zAOgNzTi9PYOO37Bx_H4Eor_c49fOV8Z98yjQlrImbcGq4vZD87L_BQ

###

get http://localhost:8091/pass?pass=admin1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluMUBhZG1pbjEuY29tIiwiYXV0aG9yaXRpZXMiOlsiR2VyZW50ZSJdLCJpYXQiOjE2NDg0NTY4NTksImV4cCI6MTY0ODQ1NzQ1OX0.Dbgw4Gg5CNEmmV1ikqf14wCOI65v94_zAOgNzTi9PYOO37Bx_H4Eor_c49fOV8Z98yjQlrImbcGq4vZD87L_BQ

###

get http://localhost:8091/val?pass=kk&cmp=$2a$10$cksJ4yIgviFz4vw1grBLcuOCYUuDgcFqEgKeuXTXYHg9/q0VwXOKa
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluMUBhZG1pbjEuY29tIiwiYXV0aG9yaXRpZXMiOlsiR2VyZW50ZSJdLCJpYXQiOjE2NDg0NTY4NTksImV4cCI6MTY0ODQ1NzQ1OX0.Dbgw4Gg5CNEmmV1ikqf14wCOI65v94_zAOgNzTi9PYOO37Bx_H4Eor_c49fOV8Z98yjQlrImbcGq4vZD87L_BQ


###
get http://localhost:8001/demos/auth/seguro
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluMUBhZG1pbjEuY29tIiwiYXV0aG9yaXRpZXMiOlsiR2VyZW50ZSJdLCJpYXQiOjE2NDg0NTY4NTksImV4cCI6MTY0ODQ1NzQ1OX0.Dbgw4Gg5CNEmmV1ikqf14wCOI65v94_zAOgNzTi9PYOO37Bx_H4Eor_c49fOV8Z98yjQlrImbcGq4vZD87L_BQ


###
get http://localhost:8001/demos/auth/secreto
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluMUBhZG1pbjEuY29tIiwiYXV0aG9yaXRpZXMiOlsiR2VyZW50ZSJdLCJpYXQiOjE2NDg0NTY4NTksImV4cCI6MTY0ODQ1NzQ1OX0.Dbgw4Gg5CNEmmV1ikqf14wCOI65v94_zAOgNzTi9PYOO37Bx_H4Eor_c49fOV8Z98yjQlrImbcGq4vZD87L_BQ
